server:
  port: 8083

spring:
  application:
    name: analytics-service
  datasource:
    url: ${ANALYTICS_DB_URL:jdbc:postgresql://localhost:5432/url_analytics}
    username: ${ANALYTICS_DB_USERNAME:postgres}
    password: ${ANALYTICS_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  topics:
    url-accessed: url-accessed-events
