FROM maven:3.9.8-eclipse-temurin-17 AS build
WORKDIR /workspace
COPY . .
RUN mvn -pl url-shortening-service -am package -DskipTests

FROM eclipse-temurin:17-jre
COPY --from=build /workspace/url-shortening-service/target/url-shortening-service-1.0.0.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
